import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

import {
  defaultManifestPath,
  loadAssetManifest,
  releaseTargets,
  sha256File,
  verifyTargetAssets,
  type ReleaseAssetManifest,
  type ReleaseTarget,
  type VerifiedAsset,
} from "./verify-ffmpeg-assets.ts";

const repoRoot = resolve(import.meta.dirname, "..");
const sourceNoticePath = resolve(repoRoot, "THIRD_PARTY_NOTICES.md");

function fail(message: string): never {
  throw new Error(message);
}

function option(args: string[], name: string): string | undefined {
  const index = args.indexOf(name);
  return index === -1 ? undefined : args[index + 1];
}

function stableSourceNotice(manifest: ReleaseAssetManifest): string {
  const lines = [
    "# LumaFlow third-party notices",
    "",
    "LumaFlow distributes FFmpeg and FFprobe as separate release assets. The exact archive, version, provider, and SHA-256 identity are locked in `scripts/ffmpeg-assets.json`; release jobs must verify those values before packaging.",
    "",
    "## FFmpeg / FFprobe",
    "",
    "FFmpeg is licensed under GPL-3.0-or-later for the selected builds. FFprobe is distributed as part of the same FFmpeg build and has the same licensing obligations. The corresponding FFmpeg source and license text are available from the provider recorded below.",
    "",
    "| Release target | FFmpeg version | Provider | Archive SHA-256 | Source |",
    "| --- | --- | --- | --- | --- |",
  ];
  for (const target of releaseTargets) {
    const asset = manifest.targets[target];
    lines.push(
      `| ${target} | ${manifest.ffmpegVersion} | ${asset.provider ?? "unspecified"} | ${asset.archive.sha256} | ${asset.sourceUrl ?? "unspecified"} |`,
    );
  }
  lines.push(
    "",
    "## License handling",
    "",
    "Release builds include the upstream license and notice files extracted from the exact verified archive under the packaged resource directory. The release workflow also records the exact `-version`, build configuration, enabled external libraries, and checksums of the two executables in a target-specific generated notice. A missing, stale, or mismatched notice fails the release gate.",
    "",
    "The FFmpeg source code is available at [ffmpeg.org](https://ffmpeg.org/) and the provider/source links above. LumaFlow does not commit the release binaries to source control; they are injected into the release job after archive verification.",
    "",
  );
  return lines.join("\n");
}

function licenseFiles(asset: VerifiedAsset): Array<{ path: string; sha256: string }> {
  const directory = resolve(asset.assetDirectory, "licenses");
  if (!existsSync(directory) || !statSync(directory).isDirectory()) {
    fail("License files are absent for " + asset.target + ": " + directory);
  }
  const files = readdirSync(directory)
    .map((name) => resolve(directory, name))
    .filter((path) => statSync(path).isFile())
    .sort();
  if (files.length === 0) {
    fail("License files are absent for " + asset.target + ": " + directory);
  }
  return files.map((path) => ({ path: path.slice(asset.assetDirectory.length + 1), sha256: sha256File(path) }));
}

function buildConfiguration(asset: VerifiedAsset): { raw: string; libraries: string[] } {
  const path = resolve(asset.assetDirectory, "ffmpeg-buildconf.txt");
  if (!existsSync(path)) {
    fail("FFmpeg build metadata is absent for " + asset.target + ": " + path);
  }
  const raw = readFileSync(path, "utf8").trim();
  if (!raw.includes("configuration:")) {
    fail("FFmpeg build metadata is invalid for " + asset.target + ": missing configuration line");
  }
  const libraries = [...raw.matchAll(/--enable-lib([a-z0-9_+-]+)/giu)].map((match) => match[1]!).sort();
  return { raw, libraries };
}

function generatedTargetNotice(asset: VerifiedAsset): string {
  const configuration = buildConfiguration(asset);
  const notices = licenseFiles(asset);
  const lines = [
    "# LumaFlow third-party notices",
    "",
    `Generated from the verified ${asset.target} FFmpeg release asset. Do not edit this file by hand.`,
    "",
    "## Verified FFmpeg / FFprobe identity",
    "",
    `- Target: ${asset.target}`,
    `- FFmpeg version: ${asset.ffmpeg.version}`,
    `- FFmpeg ` + "`-version`" + `: ${asset.ffmpeg.versionLine}`,
    `- FFmpeg SHA-256: ${asset.ffmpeg.sha256}`,
    `- FFprobe version: ${asset.ffprobe.version}`,
    `- FFprobe ` + "`-version`" + `: ${asset.ffprobe.versionLine}`,
    `- FFprobe SHA-256: ${asset.ffprobe.sha256}`,
    `- Source archive: ${asset.manifest.sourceUrl ?? "unspecified"}`,
    `- Source archive SHA-256: ${asset.archive.sha256}`,
    "",
    "## Build metadata",
    "",
    `- Configuration: ${configuration.raw}`,
    `- Enabled external libraries: ${configuration.libraries.length > 0 ? configuration.libraries.join(", ") : "none"}`,
    "",
    "## License files included with the asset",
    "",
    "FFmpeg is licensed under GPL-3.0-or-later for this build. FFprobe is part of the same FFmpeg distribution. The exact upstream license files included in the verified archive are:",
    "",
  ];
  lines.push(...notices.map((notice) => `- \`${notice.path}\` — SHA-256 ${notice.sha256}`));
  lines.push(
    "",
    "The FFmpeg source is available at [ffmpeg.org](https://ffmpeg.org/). This notice must remain alongside the packaged binaries.",
    "",
  );
  return lines.join("\n");
}

function sourceCheck(manifestPath: string): void {
  const manifest = loadAssetManifest(manifestPath);
  const expected = stableSourceNotice(manifest);
  if (!existsSync(sourceNoticePath)) {
    fail("THIRD_PARTY_NOTICES.md is absent: " + sourceNoticePath);
  }
  const actual = readFileSync(sourceNoticePath, "utf8").replace(/\r\n/gu, "\n");
  if (actual !== expected) {
    fail("THIRD_PARTY_NOTICES.md does not match scripts/ffmpeg-assets.json; regenerate the notice from the lock");
  }
  console.log("Verified source third-party notice against the release asset lock");
}

function targetCheck(args: string[], manifestPath: string): void {
  const target = option(args, "--target") as ReleaseTarget | undefined;
  if (!target || !releaseTargets.includes(target)) {
    fail("--target must be one of " + releaseTargets.join(", "));
  }
  const asset = verifyTargetAssets(target, {
    assetDirectory: option(args, "--asset-dir"),
    archivePath: option(args, "--archive"),
    manifestPath,
  });
  const expected = generatedTargetNotice(asset);
  const noticePath = resolve(option(args, "--notice") ?? resolve(asset.assetDirectory, "THIRD_PARTY_NOTICES.md"));
  if (args.includes("--write")) {
    writeFileSync(noticePath, expected, "utf8");
  }
  if (!existsSync(noticePath) || readFileSync(noticePath, "utf8").replace(/\r\n/gu, "\n") !== expected) {
    fail("Third-party notice does not match verified assets for " + target + ": " + noticePath);
  }
  console.log("Verified third-party notice for " + target);
}

function main(): void {
  const args = process.argv.slice(2);
  const manifestPath = option(args, "--manifest") ?? defaultManifestPath;
  if (args.includes("--write-source")) {
    const manifest = loadAssetManifest(manifestPath);
    writeFileSync(sourceNoticePath, stableSourceNotice(manifest), "utf8");
    return;
  }
  if (args.includes("--source-only") || !args.includes("--target")) {
    sourceCheck(manifestPath);
    return;
  }
  targetCheck(args, manifestPath);
}

const invokedScript = process.argv[1] ? resolve(process.argv[1]) : "";
if (invokedScript === resolve(import.meta.filename)) {
  try {
    main();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
